/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.sb2.training.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Doctor service. Represents a row in the &quot;mysbns_doctor&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.sb2.training.model.impl.DoctorModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.sb2.training.model.impl.DoctorImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Doctor
 * @generated
 */
@ProviderType
public interface DoctorModel extends BaseModel<Doctor> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a doctor model instance should use the {@link Doctor} interface instead.
	 */

	/**
	 * Returns the primary key of this doctor.
	 *
	 * @return the primary key of this doctor
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this doctor.
	 *
	 * @param primaryKey the primary key of this doctor
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the doc ID of this doctor.
	 *
	 * @return the doc ID of this doctor
	 */
	public long getDocId();

	/**
	 * Sets the doc ID of this doctor.
	 *
	 * @param docId the doc ID of this doctor
	 */
	public void setDocId(long docId);

	/**
	 * Returns the name of this doctor.
	 *
	 * @return the name of this doctor
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this doctor.
	 *
	 * @param name the name of this doctor
	 */
	public void setName(String name);

	/**
	 * Returns the speciality of this doctor.
	 *
	 * @return the speciality of this doctor
	 */
	@AutoEscape
	public String getSpeciality();

	/**
	 * Sets the speciality of this doctor.
	 *
	 * @param speciality the speciality of this doctor
	 */
	public void setSpeciality(String speciality);

}