/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.training.mysb.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Salary service. Represents a row in the &quot;MyFirstSbNs_Salary&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.training.mysb.model.impl.SalaryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.training.mysb.model.impl.SalaryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Salary
 * @generated
 */
@ProviderType
public interface SalaryModel extends BaseModel<Salary> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a salary model instance should use the {@link Salary} interface instead.
	 */

	/**
	 * Returns the primary key of this salary.
	 *
	 * @return the primary key of this salary
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this salary.
	 *
	 * @param primaryKey the primary key of this salary
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this salary.
	 *
	 * @return the uuid of this salary
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this salary.
	 *
	 * @param uuid the uuid of this salary
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the sal ID of this salary.
	 *
	 * @return the sal ID of this salary
	 */
	public long getSalId();

	/**
	 * Sets the sal ID of this salary.
	 *
	 * @param salId the sal ID of this salary
	 */
	public void setSalId(long salId);

	/**
	 * Returns the amount of this salary.
	 *
	 * @return the amount of this salary
	 */
	public long getAmount();

	/**
	 * Sets the amount of this salary.
	 *
	 * @param amount the amount of this salary
	 */
	public void setAmount(long amount);

	/**
	 * Returns the employee ID of this salary.
	 *
	 * @return the employee ID of this salary
	 */
	public long getEmployeeId();

	/**
	 * Sets the employee ID of this salary.
	 *
	 * @param employeeId the employee ID of this salary
	 */
	public void setEmployeeId(long employeeId);

}