/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.sb2.training.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the XyzOrg service. Represents a row in the &quot;vt_XyzOrg&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.sb2.training.model.impl.XyzOrgModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.sb2.training.model.impl.XyzOrgImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see XyzOrg
 * @generated
 */
@ProviderType
public interface XyzOrgModel extends BaseModel<XyzOrg> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a xyz org model instance should use the {@link XyzOrg} interface instead.
	 */

	/**
	 * Returns the primary key of this xyz org.
	 *
	 * @return the primary key of this xyz org
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this xyz org.
	 *
	 * @param primaryKey the primary key of this xyz org
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this xyz org.
	 *
	 * @return the uuid of this xyz org
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this xyz org.
	 *
	 * @param uuid the uuid of this xyz org
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the dep ID of this xyz org.
	 *
	 * @return the dep ID of this xyz org
	 */
	public long getDepId();

	/**
	 * Sets the dep ID of this xyz org.
	 *
	 * @param depId the dep ID of this xyz org
	 */
	public void setDepId(long depId);

	/**
	 * Returns the dep name of this xyz org.
	 *
	 * @return the dep name of this xyz org
	 */
	@AutoEscape
	public String getDepName();

	/**
	 * Sets the dep name of this xyz org.
	 *
	 * @param depName the dep name of this xyz org
	 */
	public void setDepName(String depName);

}