/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.training.mysb.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import com.training.mysb.model.Salary;
import com.training.mysb.model.SalaryModel;
import com.training.mysb.model.SalarySoap;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model implementation for the Salary service. Represents a row in the &quot;MyFirstSbNs_Salary&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>SalaryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SalaryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SalaryImpl
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class SalaryModelImpl
	extends BaseModelImpl<Salary> implements SalaryModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a salary model instance should use the <code>Salary</code> interface instead.
	 */
	public static final String TABLE_NAME = "MyFirstSbNs_Salary";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"salId", Types.BIGINT},
		{"amount", Types.BIGINT}, {"employeeId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("salId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("amount", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("employeeId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table MyFirstSbNs_Salary (uuid_ VARCHAR(75) null,salId LONG not null primary key,amount LONG,employeeId LONG)";

	public static final String TABLE_SQL_DROP = "drop table MyFirstSbNs_Salary";

	public static final String ORDER_BY_JPQL = " ORDER BY salary.salId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY MyFirstSbNs_Salary.salId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long UUID_COLUMN_BITMASK = 1L;

	public static final long SALID_COLUMN_BITMASK = 2L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Salary toModel(SalarySoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Salary model = new SalaryImpl();

		model.setUuid(soapModel.getUuid());
		model.setSalId(soapModel.getSalId());
		model.setAmount(soapModel.getAmount());
		model.setEmployeeId(soapModel.getEmployeeId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Salary> toModels(SalarySoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Salary> models = new ArrayList<Salary>(soapModels.length);

		for (SalarySoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public SalaryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _salId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setSalId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _salId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Salary.class;
	}

	@Override
	public String getModelClassName() {
		return Salary.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Salary, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Salary, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Salary, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Salary)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Salary, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Salary, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Salary)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Salary, Object>> getAttributeGetterFunctions() {
		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Salary, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, Salary>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			Salary.class.getClassLoader(), Salary.class, ModelWrapper.class);

		try {
			Constructor<Salary> constructor =
				(Constructor<Salary>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map<String, Function<Salary, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Salary, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Salary, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Salary, Object>>();
		Map<String, BiConsumer<Salary, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Salary, ?>>();

		attributeGetterFunctions.put("uuid", Salary::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<Salary, String>)Salary::setUuid);
		attributeGetterFunctions.put("salId", Salary::getSalId);
		attributeSetterBiConsumers.put(
			"salId", (BiConsumer<Salary, Long>)Salary::setSalId);
		attributeGetterFunctions.put("amount", Salary::getAmount);
		attributeSetterBiConsumers.put(
			"amount", (BiConsumer<Salary, Long>)Salary::setAmount);
		attributeGetterFunctions.put("employeeId", Salary::getEmployeeId);
		attributeSetterBiConsumers.put(
			"employeeId", (BiConsumer<Salary, Long>)Salary::setEmployeeId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getSalId() {
		return _salId;
	}

	@Override
	public void setSalId(long salId) {
		_salId = salId;
	}

	@JSON
	@Override
	public long getAmount() {
		return _amount;
	}

	@Override
	public void setAmount(long amount) {
		_amount = amount;
	}

	@JSON
	@Override
	public long getEmployeeId() {
		return _employeeId;
	}

	@Override
	public void setEmployeeId(long employeeId) {
		_employeeId = employeeId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, Salary.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Salary toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Salary>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SalaryImpl salaryImpl = new SalaryImpl();

		salaryImpl.setUuid(getUuid());
		salaryImpl.setSalId(getSalId());
		salaryImpl.setAmount(getAmount());
		salaryImpl.setEmployeeId(getEmployeeId());

		salaryImpl.resetOriginalValues();

		return salaryImpl;
	}

	@Override
	public int compareTo(Salary salary) {
		long primaryKey = salary.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Salary)) {
			return false;
		}

		Salary salary = (Salary)obj;

		long primaryKey = salary.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		SalaryModelImpl salaryModelImpl = this;

		salaryModelImpl._originalUuid = salaryModelImpl._uuid;

		salaryModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Salary> toCacheModel() {
		SalaryCacheModel salaryCacheModel = new SalaryCacheModel();

		salaryCacheModel.uuid = getUuid();

		String uuid = salaryCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			salaryCacheModel.uuid = null;
		}

		salaryCacheModel.salId = getSalId();

		salaryCacheModel.amount = getAmount();

		salaryCacheModel.employeeId = getEmployeeId();

		return salaryCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Salary, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Salary, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Salary, Object> attributeGetterFunction = entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((Salary)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Salary, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Salary, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Salary, Object> attributeGetterFunction = entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Salary)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Salary>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private String _uuid;
	private String _originalUuid;
	private long _salId;
	private long _amount;
	private long _employeeId;
	private long _columnBitmask;
	private Salary _escapedModel;

}